// A simple in-memory store to simulate a database for the mock environment
import type { TranscriptTask } from "@/components/transcript-list"

// Using a global variable that persists across hot-reloads in development
const globalForStore = global as unknown as { tasks: TranscriptTask[] }
export const tasksStore = globalForStore.tasks || []

if (process.env.NODE_ENV !== "production") globalForStore.tasks = tasksStore

export function addTask(task: TranscriptTask) {
  tasksStore.unshift(task)
  // Simulate processing
  simulateProcessing(task.id)
}

function simulateProcessing(id: string) {
  let progress = 0
  const interval = setInterval(() => {
    const taskIndex = tasksStore.findIndex((t) => t.id === id)
    if (taskIndex === -1) {
      clearInterval(interval)
      return
    }

    progress += Math.floor(Math.random() * 20) + 10
    if (progress >= 100) {
      progress = 100
      clearInterval(interval)
      const isSuccess = Math.random() > 0.1
      tasksStore[taskIndex] = {
        ...tasksStore[taskIndex],
        status: isSuccess ? "completed" : "failed",
        progress: 100,
        transcript: isSuccess
          ? "This is a completed transcript generated by the background process. It correctly identified all the speech in your uploaded file."
          : undefined,
        error: isSuccess ? undefined : "Internal processing error occurred.",
      }
    } else {
      tasksStore[taskIndex] = { ...tasksStore[taskIndex], progress }
    }
  }, 1500)
}
